baseURL = "https://hanedan.github.io/kalemim/"
languageCode = "en-us"
title = "My Blog"
theme = "tokiwa"

copyright = "Copyright © 2025"


[markup]
[markup.highlight]
style = "monokailight"

[params]
  description = "This is my personal blog."

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 3  # Adjust the weight to change the order in the menu


[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10  # Adjust the weight to change the order in the menu
